# baseURL = 'http://example.org/' # Set in the GitHub Actions as a command line arg
languageCode = 'en-us'
title = 'Salawaat Hub'

######################
# Theme Theme Config
######################
theme = "hugo-book"
[params]
# In the left-handside display, show all the pages inthe content/
BookSection = '*'

[markup.tableOfContents]
startLevel = 1
